- repo: https://github.com/psf/black
  rev: 22.3.0  # Use the latest version of black
  hooks:
    - id: black
      language_version: python3

- repo: https://github.com/pycqa/flake8
  rev: v5.0.0
  hooks:
    - id: flake8
      args: ['--max-line-length=88']

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.990
  hooks:
    - id: mypy
      args: ['--files', 'app']
