name: Code Quality and Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run flake8 (Linting)
        run: |
          flake8 app

      - name: Run Bandit (Security)
        run: |
          bandit -r app

      - name: Run Black (Formatting)
        run: |
          black --check .

      - name: Run Mypy (Type Checking)
        run: |
          mypy app
