name: Docker Image Vulnerability Scan with Trivy

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (enables building Docker images with advanced features)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub (optional if you want to push images)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-python-app:latest -f docker/Dockerfile .

      # Step 5: Install Trivy
      - name: Install Trivy
        run: |
          curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.43.0/trivy_0.43.0_Linux-64bit.deb -o trivy.deb
          sudo dpkg -i trivy.deb

      # Step 6: Scan Docker image with Trivy
      - name: Run Trivy scan on Docker image
        run: |
          trivy image --exit-code 1 --no-progress my-python-app:latest

      # Optional: Step 7: Upload Trivy scan results (if you want to push results to another service)
      # - name: Upload scan results to a service (e.g., GitHub Actions artifacts)
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: trivy-scan-results
      #     path: trivy-report.json
